/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/kavis/.choosenim/toolchains/nim-0.18.0/lib -o /home/kavis/Documents/Programming/Nim/Tutorial/Book/Chap2/nimcache/order_proc.o /home/kavis/Documents/Programming/Nim/Tutorial/Book/Chap2/nimcache/order_proc.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_24KAM9afIUgUaqBaEBB6r9bg[3];
N_LIB_PRIVATE N_NIMCALL(NF, foo_IyRaQcgwQ04OJU7Li1fZEQ)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NI, bar_Sn4g8V4yOgy66aBavDxtNw)(void);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, nimFloatToStr)(NF f);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, order_procDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_0oOi3Y4t4UGP9aByUpfQdiw_2, "\012", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NF, foo_IyRaQcgwQ04OJU7Li1fZEQ)(void) {
	NF result;
	NI T1_;
	nimfr_("foo", "order_proc.nim");
	result = (NF)0;
	nimln_(3, "order_proc.nim");
	T1_ = (NI)0;
	T1_ = bar_Sn4g8V4yOgy66aBavDxtNw();
	result = ((NF) (T1_));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, bar_Sn4g8V4yOgy66aBavDxtNw)(void) {
	NI result;
	nimfr_("bar", "order_proc.nim");
	result = (NI)0;
	nimln_(4, "order_proc.nim");
	result = ((NI) 3);
	popFrame();
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	order_procDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyArray_24KAM9afIUgUaqBaEBB6r9bg T1_;
	NI T2_;
	NF T3_;
	nimfr_("order_proc", "order_proc.nim");
	nimln_(6, "order_proc.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T2_ = (NI)0;
	T2_ = bar_Sn4g8V4yOgy66aBavDxtNw();
	T1_[0] = nimIntToStr(T2_);
	T1_[1] = copyString(((NimStringDesc*) &TM_0oOi3Y4t4UGP9aByUpfQdiw_2));
	T3_ = (NF)0;
	T3_ = foo_IyRaQcgwQ04OJU7Li1fZEQ();
	T1_[2] = nimFloatToStr(T3_);
	echoBinSafe(T1_, 3);
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, order_procDatInit000)(void) {
}

