/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/kavis/.choosenim/toolchains/nim-0.18.0/lib -o /home/kavis/Documents/Programming/Nim/Tutorial/Book/Chap2/nimcache/proc_style.o /home/kavis/Documents/Programming/Nim/Tutorial/Book/Chap2/nimcache/proc_style.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, implicit_uDWJIdxTdxZ9chKjleI4bEA)(void);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, discarded_uDWJIdxTdxZ9chKjleI4bEA_2)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, explicit_uDWJIdxTdxZ9chKjleI4bEA_3)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resultVar_uDWJIdxTdxZ9chKjleI4bEA_4)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resultVar2_uDWJIdxTdxZ9chKjleI4bEA_5)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resultAuto_uDWJIdxTdxZ9chKjleI4bEA_6)(void);
N_LIB_PRIVATE N_NIMCALL(void, main_Z5BE07TwaPNy9cn08D9cMEKA)(void);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, proc_styleDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_DZ7oyXNLW2ieU9bFq9aHirJg_2, "I will be returned", 18);
STRING_LITERAL(TM_DZ7oyXNLW2ieU9bFq9aHirJg_3, "", 0);
STRING_LITERAL(TM_DZ7oyXNLW2ieU9bFq9aHirJg_4, "I will be ", 10);
STRING_LITERAL(TM_DZ7oyXNLW2ieU9bFq9aHirJg_5, "returned", 8);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, implicit_uDWJIdxTdxZ9chKjleI4bEA)(void) {
	NimStringDesc* result;
	nimfr_("implicit", "proc_style.nim");
	result = (NimStringDesc*)0;
	nimln_(2, "proc_style.nim");
	result = copyString(((NimStringDesc*) &TM_DZ7oyXNLW2ieU9bFq9aHirJg_2));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, discarded_uDWJIdxTdxZ9chKjleI4bEA_2)(void) {
	NimStringDesc* result;
	nimfr_("discarded", "proc_style.nim");
	result = (NimStringDesc*)0;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, explicit_uDWJIdxTdxZ9chKjleI4bEA_3)(void) {
	NimStringDesc* result;
	nimfr_("explicit", "proc_style.nim");
{	result = (NimStringDesc*)0;
	nimln_(8, "proc_style.nim");
	result = copyString(((NimStringDesc*) &TM_DZ7oyXNLW2ieU9bFq9aHirJg_2));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resultVar_uDWJIdxTdxZ9chKjleI4bEA_4)(void) {
	NimStringDesc* result;
	nimfr_("resultVar", "proc_style.nim");
	result = (NimStringDesc*)0;
	nimln_(11, "proc_style.nim");
	result = copyString(((NimStringDesc*) &TM_DZ7oyXNLW2ieU9bFq9aHirJg_2));
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resultVar2_uDWJIdxTdxZ9chKjleI4bEA_5)(void) {
	NimStringDesc* result;
	nimfr_("resultVar2", "proc_style.nim");
	result = (NimStringDesc*)0;
	nimln_(14, "proc_style.nim");
	result = copyString(((NimStringDesc*) &TM_DZ7oyXNLW2ieU9bFq9aHirJg_3));
	nimln_(15, "proc_style.nim");
	result = resizeString(result, 10);
appendString(result, ((NimStringDesc*) &TM_DZ7oyXNLW2ieU9bFq9aHirJg_4));
	nimln_(16, "proc_style.nim");
	result = resizeString(result, 8);
appendString(result, ((NimStringDesc*) &TM_DZ7oyXNLW2ieU9bFq9aHirJg_5));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, resultAuto_uDWJIdxTdxZ9chKjleI4bEA_6)(void) {
	NimStringDesc* result;
	nimfr_("resultAuto", "proc_style.nim");
	result = (NimStringDesc*)0;
	nimln_(19, "proc_style.nim");
	result = copyString(((NimStringDesc*) &TM_DZ7oyXNLW2ieU9bFq9aHirJg_2));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, main_Z5BE07TwaPNy9cn08D9cMEKA)(void) {
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T2_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T3_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T4_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T5_;
	tyArray_nHXaesL0DJZHyVS07ARPRA T6_;
	nimfr_("main", "proc_style.nim");
	nimln_(22, "proc_style.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = implicit_uDWJIdxTdxZ9chKjleI4bEA();
	echoBinSafe(T1_, 1);
	nimln_(23, "proc_style.nim");
	memset((void*)T2_, 0, sizeof(T2_));
	T2_[0] = explicit_uDWJIdxTdxZ9chKjleI4bEA_3();
	echoBinSafe(T2_, 1);
	nimln_(24, "proc_style.nim");
	memset((void*)T3_, 0, sizeof(T3_));
	T3_[0] = discarded_uDWJIdxTdxZ9chKjleI4bEA_2();
	echoBinSafe(T3_, 1);
	nimln_(25, "proc_style.nim");
	memset((void*)T4_, 0, sizeof(T4_));
	T4_[0] = resultVar_uDWJIdxTdxZ9chKjleI4bEA_4();
	echoBinSafe(T4_, 1);
	nimln_(26, "proc_style.nim");
	memset((void*)T5_, 0, sizeof(T5_));
	T5_[0] = resultVar2_uDWJIdxTdxZ9chKjleI4bEA_5();
	echoBinSafe(T5_, 1);
	nimln_(27, "proc_style.nim");
	memset((void*)T6_, 0, sizeof(T6_));
	T6_[0] = resultAuto_uDWJIdxTdxZ9chKjleI4bEA_6();
	echoBinSafe(T6_, 1);
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	proc_styleDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("proc_style", "proc_style.nim");
	nimln_(29, "proc_style.nim");
	{
		if (!NIM_TRUE) goto LA3_;
		nimln_(30, "proc_style.nim");
		main_Z5BE07TwaPNy9cn08D9cMEKA();
	}
	LA3_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, proc_styleDatInit000)(void) {
}

