/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/kavis/.choosenim/toolchains/nim-0.18.0/lib -o /home/kavis/Documents/Programming/Nim/Tutorial/Book/Chap2/nimcache/varargs.o /home/kavis/Documents/Programming/Nim/Tutorial/Book/Chap2/nimcache/varargs.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, genHello_pueYYqeClf0vhcphkQbzSw)(NimStringDesc** names, NI namesLen_0);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, varargsDatInit000)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_o1b6wn50XvXtRRieZaSXJQ_2, "", 0);
STRING_LITERAL(TM_o1b6wn50XvXtRRieZaSXJQ_3, "Hello ", 6);
STRING_LITERAL(TM_o1b6wn50XvXtRRieZaSXJQ_4, "\012", 1);
STRING_LITERAL(TM_o1b6wn50XvXtRRieZaSXJQ_7, "John", 4);
STRING_LITERAL(TM_o1b6wn50XvXtRRieZaSXJQ_8, "Bob", 3);
NIM_CONST tyArray_Re75IspeoxXy2oCZHwcRrA TM_o1b6wn50XvXtRRieZaSXJQ_6 = {((NimStringDesc*) &TM_o1b6wn50XvXtRRieZaSXJQ_7),
((NimStringDesc*) &TM_o1b6wn50XvXtRRieZaSXJQ_8)}
;
STRING_LITERAL(TM_o1b6wn50XvXtRRieZaSXJQ_9, "Hello John\012Hello Bob\012", 21);
STRING_LITERAL(TM_o1b6wn50XvXtRRieZaSXJQ_10, "genHello([\"John\", \"Bob\"]) == \"Hello John\\LHello Bob\\L\" ", 55);

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, genHello_pueYYqeClf0vhcphkQbzSw)(NimStringDesc** names, NI namesLen_0) {
	NimStringDesc* result;
	nimfr_("genHello", "varargs.nim");
	result = (NimStringDesc*)0;
	nimln_(2, "varargs.nim");
	result = copyString(((NimStringDesc*) &TM_o1b6wn50XvXtRRieZaSXJQ_2));
	{
		NimStringDesc* name;
		NI i;
		name = (NimStringDesc*)0;
		nimln_(2185, "system.nim");
		i = ((NI) 0);
		{
			nimln_(2186, "system.nim");
			while (1) {
				NimStringDesc* T4_;
				NI TM_o1b6wn50XvXtRRieZaSXJQ_5;
				if (!(i < namesLen_0)) goto LA3;
				nimln_(2187, "system.nim");
				if ((NU)(i) >= (NU)(namesLen_0)) raiseIndexError();
				name = names[i];
				nimln_(4, "varargs.nim");
				T4_ = (NimStringDesc*)0;
				T4_ = rawNewString(name->Sup.len + 7);
appendString(T4_, ((NimStringDesc*) &TM_o1b6wn50XvXtRRieZaSXJQ_3));
appendString(T4_, name);
appendString(T4_, ((NimStringDesc*) &TM_o1b6wn50XvXtRRieZaSXJQ_4));
				result = resizeString(result, T4_->Sup.len + 0);
appendString(result, T4_);
				nimln_(2188, "system.nim");
				TM_o1b6wn50XvXtRRieZaSXJQ_5 = addInt(i, ((NI) 1));
				i = (NI)(TM_o1b6wn50XvXtRRieZaSXJQ_5);
			} LA3: ;
		}
	}
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	varargsDatInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("varargs", "varargs.nim");
	nimln_(6, "varargs.nim");
	{
		NimStringDesc* T3_;
		T3_ = (NimStringDesc*)0;
		T3_ = genHello_pueYYqeClf0vhcphkQbzSw(TM_o1b6wn50XvXtRRieZaSXJQ_6, 2);
		if (!!(eqStrings(T3_, ((NimStringDesc*) &TM_o1b6wn50XvXtRRieZaSXJQ_9)))) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_o1b6wn50XvXtRRieZaSXJQ_10));
	}
	LA4_: ;
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, varargsDatInit000)(void) {
}

